[agent]
  interval = "10s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "admin:prometheus123"  # Формат: "username:password"
  organization = "myorg"
  bucket = "metrics"

[[inputs.cpu]]
[[inputs.mem]]
[[inputs.disk]]
[[inputs.diskio]]
[[inputs.net]]
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"

