// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkWGyTuQk66GQ3pz1PEuVI-8O1N6q7uos',
    appId: '1:297233484010:web:8ebd3d1cdde058e8f1ef93',
    messagingSenderId: '297233484010',
    projectId: 'playgameflutterfinal',
    authDomain: 'playgameflutterfinal.firebaseapp.com',
    storageBucket: 'playgameflutterfinal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-jbXKof9M3z6kc21PCVIHKR0fnS1BAX0',
    appId: '1:297233484010:android:0e957622bad82d89f1ef93',
    messagingSenderId: '297233484010',
    projectId: 'playgameflutterfinal',
    storageBucket: 'playgameflutterfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy1_eCINJlTH7ZFkXLvh3J6iqudtj19bs',
    appId: '1:297233484010:ios:943b91e061e4dd62f1ef93',
    messagingSenderId: '297233484010',
    projectId: 'playgameflutterfinal',
    storageBucket: 'playgameflutterfinal.firebasestorage.app',
    iosClientId: '297233484010-2qf4p8mgivcufc3h4erb15rsoq7v2ci4.apps.googleusercontent.com',
    iosBundleId: 'com.example.playgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy1_eCINJlTH7ZFkXLvh3J6iqudtj19bs',
    appId: '1:297233484010:ios:943b91e061e4dd62f1ef93',
    messagingSenderId: '297233484010',
    projectId: 'playgameflutterfinal',
    storageBucket: 'playgameflutterfinal.firebasestorage.app',
    iosClientId: '297233484010-2qf4p8mgivcufc3h4erb15rsoq7v2ci4.apps.googleusercontent.com',
    iosBundleId: 'com.example.playgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkWGyTuQk66GQ3pz1PEuVI-8O1N6q7uos',
    appId: '1:297233484010:web:5c90c0a4351a4bf0f1ef93',
    messagingSenderId: '297233484010',
    projectId: 'playgameflutterfinal',
    authDomain: 'playgameflutterfinal.firebaseapp.com',
    storageBucket: 'playgameflutterfinal.firebasestorage.app',
  );
}
